# Generated by Django 5.0.6 on 2024-07-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("subtitle", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.IntegerField(blank=True, null=True)),
                (
                    "discount",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=6, null=True
                    ),
                ),
                ("image", models.JSONField(blank=True, null=True)),
                ("ratting", models.TextField(blank=True, null=True)),
                ("date", models.DateTimeField(auto_now=True, null=True)),
                ("quantity", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Item",
        ),
    ]
